FROM centos:7.6.1810

ENV OS_VERSION=7.6.1810 \
    HTTP_PROXY=http://10.158.100.2:8080 \
    HTTPS_PROXY=http://10.158.100.2:8080 \
    http_proxy=http://10.158.100.2:8080 \
    https_proxy=http://10.158.100.2:8080 

# No Need Update below
RUN echo "proxy=${HTTP_PROXY}" >> /etc/yum.conf && \
    yum install -y epel-release

RUN yum install -y atop iftop htop iotop nethogs \
                   tcpdump iproute iputils net-tools \
                   ethtool traceroute nmap nmap-ncat nmon \
                   strace iperf3 qperf lsof bind-utils wget && \
    yum clean all
